// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Caml_format = require("bs-platform/lib/js/caml_format.js");
var HomeConstants$ReactTemplate = require("./HomeConstants.bs.js");

function multiplyByRandomValue(max, min, value) {
  return Caml_format.caml_float_of_string((value * (Math.random() * (min - max) + max)).toFixed(5));
}

function shouldPairUpdate(param) {
  return Math.random() < HomeConstants$ReactTemplate.pairChangeProbability;
}

function multiplyByRandom(param) {
  return multiplyByRandomValue(HomeConstants$ReactTemplate.minMultiplier, HomeConstants$ReactTemplate.maxMultiplier, param);
}

function getPairWithUpdatedRate(param) {
  return /* Pair */[
          param[0],
          multiplyByRandom(param[1]),
          multiplyByRandom(param[2])
        ];
}

function mapPairs(pair) {
  var match = Math.random() < HomeConstants$ReactTemplate.pairChangeProbability;
  if (match) {
    return getPairWithUpdatedRate(pair);
  } else {
    return pair;
  }
}

exports.multiplyByRandomValue = multiplyByRandomValue;
exports.shouldPairUpdate = shouldPairUpdate;
exports.multiplyByRandom = multiplyByRandom;
exports.getPairWithUpdatedRate = getPairWithUpdatedRate;
exports.mapPairs = mapPairs;
/* No side effect */
