// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var CurrencyPair$ReactTemplate = require("../../common/components/CurrencyPair/CurrencyPair.bs.js");

var component = ReasonReact.statelessComponent("Home");

var currencyPairsMock = /* array */[
  /* Pair */[
    "USD CHF",
    0.99143,
    0.99043
  ],
  /* Pair */[
    "GBP USD",
    1.28495,
    1.2836
  ],
  /* Pair */[
    "GBP CHF",
    1.27378,
    1.27147
  ],
  /* Pair */[
    "EUR SEK",
    9.632,
    9.6055
  ],
  /* Pair */[
    "USD JPY",
    110.467,
    110.417
  ],
  /* Pair */[
    "EUR JPY",
    120.589,
    120.491
  ]
];

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */(function (_self) {
              return /* () */0;
            }),
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return React.createElement("main", undefined, $$Array.mapi((function (index, param) {
                                return ReasonReact.element(String(index), undefined, CurrencyPair$ReactTemplate.make(param[0], param[1], param[2], /* array */[]));
                              }), currencyPairsMock));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.currencyPairsMock = currencyPairsMock;
exports.make = make;
/* component Not a pure module */
