// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


var pairChangeProbability = 0.7;

var minMultiplier = 0.9;

var maxMultiplier = 1.1;

var refreshTime = 3000;

exports.pairChangeProbability = pairChangeProbability;
exports.minMultiplier = minMultiplier;
exports.maxMultiplier = maxMultiplier;
exports.refreshTime = refreshTime;
/* No side effect */
